apiVersion: v1
kind: Service
metadata:
  name: maven-service
spec:
  type: NodePort
  ports:
    - name: maven
      port: 8081
      nodePort: 31002
      targetPort: 8081
      protocol: TCP
  selector:
    app: maven
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maven-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
        - name: maven
          image: 172.20.10.9:5000/maven:latest
          ports:
            - containerPort: 8081
          env:
            - name: key
              value: "value"